#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.JJTheme >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.JJTheme=/luci-static/JJTheme
		set luci.main.mediaurlbase=/luci-static/JJTheme
		commit luci
	EOF
fi

exit 0